---
# This role installs apache2

- name: install apache2
  become: yes
  apt: name={{ item }} state=present
  with_items:
      - apache2
      - apache2-utils

- name: change default ports
  become: yes
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache2

- name: install php5 and python on apache2
  become: yes
  apt: name={{ item }} state=present
  with_items:
      - libapache2-mod-php
      - php7.2-mysql

- name: copy php.ini
  become: yes
  copy: src=php.ini dest=/etc/php/7.2/apache2/php.ini
  notify:
      - restart apache2
