- name: Create Application Database
  mysql_db:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_unix_socket: '{{ login_unix_socket }}'
    name: "{{ dbname }}"
    state: present
